### ISSUE TITLE
Office Mix App is not loading

### ISSUE THREAD

**Issue by mattpen** [phetsims/phet-office-add-in#13]
The office add-in is not launching.  It appears that one of the libraries that we are using is no longer available.  I'm assuming this is related to the sunset of office-mix.  The website for the missing library appears to have disappeared entirely: https://labsjs.blob.core.windows.net/sdk/index.html

```
store.html:105 GET https://az592748.vo.msecnd.net/sdk/LabsJS-1.0.4/labs-1.0.4.min.js net::ERR_ABORTED 404```

**Comment by mattpen** [comment]
@ariel-phet - I'm not sure how to proceed here.  Should we contact Kurt (Microsoft)?

**Comment by ariel-phet** [comment]
@mattpen I contacted Kurt, lets see what he writes back. I have a few other contacts at MS I can reach out to that might be willing to give us some technical assistance.

**Comment by ariel-phet** [comment]
Kurt said:

>  I can definitely help out.
> 
> It looks like during the transition someone accidentally deleted the blob storage account (and CDN) we were using to host our JavaScript API. And as you pointed out that then led your app to not having access. We're attempting to undo the delete on Azure but it's unclear when that will be finished.
> 
> But in the meantime - and probably better longer term given the sunset - is to just deploy and reference our files directly. I attached a zip file with what we were hosting on the CDN.
> 
> Very sorry for the disruption. PhET has always been my favorite Mix app and I still use it in my PowerPoint presentations. So definitely want to make sure to get it back up and running!

zip of relevant files:
https://1drv.ms/u/s!AhqjnDQVp5qJgdNQXyttTNEq1m805Q

**Comment by mattpen** [comment]
I added the Labs JS API to our repo and republished the app on our website.  It appears to be working normally now. @oliver-phet - Are there any users that need a follow-up?
