### ISSUE TITLE
Fourier: Making Waves missing from Office Mix app

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/phet-office-add-in#18]
A user reported into phethelp that Fourier: Making Waves is missing in the Powerpoint app. I verified that it is missing along with several newer sims:

Name | Title | Type | Created Date
-- | -- | -- | --
geometric-optics-basics | Geometric Optics: Basics | html | 2022-11-30
geometric-optics | Geometric Optics | html | 2022-04-06
density | Density | html | 2022-01-13
circuit-construction-kit-ac | Circuit Construction Kit: AC | html | 2021-12-15
circuit-construction-kit-ac-virtual-lab | Circuit Construction Kit: AC - Virtual Lab | html | 2021-12-15
fourier-making-waves | Fourier: Making Waves | html | 2021-10-13

The most recent published sim _included_ in the app is Number Line: Distance (2021-08-13).

@mattpen are you the best person to investigate what might be going on?

**Comment by mattpen** [comment]
I think the daily syncronization didn't get setup correctly when we switched to phet-server2.  I fixed a couple of errors and now the app has all of the sims you mentioned when I'm testing it on office 365.

@oliver-phet - can you check that this has been resolved?

**Comment by oliver-phet** [comment]
Looks good, thanks for fixing! I'll reply to the user.
